"""
PegFX Studio Pro — CircuitPython Standalone Player
Hardware: Adafruit MatrixPortal M4 / S3 or Raspberry Pi RP2040 Matrix Bonnet
Drop this file onto your CIRCUITPY drive alongside matrix.bmp
"""

import time
import board
import displayio
from adafruit_matrixportal.matrix import Matrix

# 1. Initialize RGB LED Matrix (Default 64x32)
matrix = Matrix(width=64, height=32, bit_depth=4)
display = matrix.display

# 2. Load the exported bitmap asset generated by PegFX
try:
    bitmap = displayio.OnDiskBitmap("matrix.bmp")
    tile_grid = displayio.TileGrid(
        bitmap,
        pixel_shader=bitmap.pixel_shader,
        width=1,
        height=1,
        tile_width=64,
        tile_height=32
    )

    group = displayio.Group()
    group.append(tile_grid)
    display.root_group = group

    print("PegFX Matrix Display Running")

    # Animation loop (Adjust delay for desired playback speed, e.g. 10 FPS = 0.1s)
    FPS = 10
    frame_delay = 1.0 / FPS

    # If the bitmap contains multiple frames, cycle through them
    frame_idx = 0
    # In CircuitPython, multi-frame sprite sheets advance via tile_grid[0]
    while True:
        tile_grid[0] = frame_idx
        frame_idx = (frame_idx + 1) % max(1, bitmap.width // 64)
except Exception as e:
    print(f"Error loading matrix asset: {e}")
    while True:
        time.sleep(1)
